### ISSUE TITLE
Add CLI for scripting?

### ISSUE THREAD

**Issue by Pysis868** [handsomematt/dont-starve-tools#4]
So far I don't see any, or batch capabilities, even when I ran the program from a console.

**Comment by handsomematt** [comment]
The official mod tools shipped with the game include an extensive CLI environment far better than this can provide.

**Comment by Pysis868** [comment]
ok
https://github.com/kleientertainment/ds_mod_tools

**Comment by Pysis868** [comment]
@HandsomeMatt Would you know which tool in the official mod tools I can use to convert `.tex` files into `.png` files?
